version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13_mund_2
    ports:
      - "5432:5432"
    networks:
      - my-net
    hostname: postgres 
  
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-net
      
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
    networks:
      - my-net
    hostname: my_app

networks:
  my-net:
